// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6tGQ9w-69Y_T0MeEeAvsSGL_Grhqd4yk',
    appId: '1:398280503958:web:f9a5f53f17db27a07a88b7',
    messagingSenderId: '398280503958',
    projectId: 'alarm-it',
    authDomain: 'alarm-it.firebaseapp.com',
    storageBucket: 'alarm-it.firebasestorage.app',
    measurementId: 'G-L27PDTHSHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC88L52c16e3G0g92Z0OC_YuxjJtNIdGOE',
    appId: '1:398280503958:android:ffb7547685050bfa7a88b7',
    messagingSenderId: '398280503958',
    projectId: 'alarm-it',
    storageBucket: 'alarm-it.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkvDyVkH_owpnJlE5Yu7Faowi3zpD6E2w',
    appId: '1:398280503958:ios:0845c84ebaa211627a88b7',
    messagingSenderId: '398280503958',
    projectId: 'alarm-it',
    storageBucket: 'alarm-it.firebasestorage.app',
    iosBundleId: 'com.example.notificationIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkvDyVkH_owpnJlE5Yu7Faowi3zpD6E2w',
    appId: '1:398280503958:ios:0845c84ebaa211627a88b7',
    messagingSenderId: '398280503958',
    projectId: 'alarm-it',
    storageBucket: 'alarm-it.firebasestorage.app',
    iosBundleId: 'com.example.notificationIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6tGQ9w-69Y_T0MeEeAvsSGL_Grhqd4yk',
    appId: '1:398280503958:web:89d44792ac8af0577a88b7',
    messagingSenderId: '398280503958',
    projectId: 'alarm-it',
    authDomain: 'alarm-it.firebaseapp.com',
    storageBucket: 'alarm-it.firebasestorage.app',
    measurementId: 'G-HRN4LSV77D',
  );

}