// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpEUJxmYleRUeFDlg9aLE6RcScsoByiy0',
    appId: '1:686539632718:web:90a9ce7dee9ea89c1b131f',
    messagingSenderId: '686539632718',
    projectId: 'alarmit--uou',
    authDomain: 'alarmit--uou.firebaseapp.com',
    storageBucket: 'alarmit--uou.firebasestorage.app',
    measurementId: 'G-VQB92LSVPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-UJb4CtxPopiJrAKodbwnEi4bCawV4Is',
    appId: '1:686539632718:android:6ca0959b22f2fdc31b131f',
    messagingSenderId: '686539632718',
    projectId: 'alarmit--uou',
    storageBucket: 'alarmit--uou.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYtXBxmXeKiqDzK5VPyDKUnOjtzBHj7BE',
    appId: '1:686539632718:ios:8f3985bd05ae84741b131f',
    messagingSenderId: '686539632718',
    projectId: 'alarmit--uou',
    storageBucket: 'alarmit--uou.firebasestorage.app',
    iosBundleId: 'com.uou.alarmit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYtXBxmXeKiqDzK5VPyDKUnOjtzBHj7BE',
    appId: '1:686539632718:ios:4cae07de119c97581b131f',
    messagingSenderId: '686539632718',
    projectId: 'alarmit--uou',
    storageBucket: 'alarmit--uou.firebasestorage.app',
    iosBundleId: 'com.example.notificationIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpEUJxmYleRUeFDlg9aLE6RcScsoByiy0',
    appId: '1:686539632718:web:8c9b43adf3ec51b01b131f',
    messagingSenderId: '686539632718',
    projectId: 'alarmit--uou',
    authDomain: 'alarmit--uou.firebaseapp.com',
    storageBucket: 'alarmit--uou.firebasestorage.app',
    measurementId: 'G-KNB00MYBLY',
  );

}