const version = '1.0.1';
const KHasSeenIntro = 'hasSeenIntro';
const kConsentKey = 'privacy_consent_v1';
const String port = 'https://alarm-it.ulsan.ac.kr/test';
const kAlarmListKey = 'alram_list';       // 선택한 학부/전공 리스트
const kIsAllAlarmOnKey = 'isAllAlarmOn';  // 전체 알림 스위치 상태
const String kMainMajorKey = 'main_major';        // Page1: 대표 전공(1개)
const String kAlarmMajorsKey = 'alarm_majors';    // Page2: 알림 받을 전공들(여러개)
const isBell = false;